// 文件职责：六个内容分类的受控标签词表（facets）与多语言显示名单一来源。
// 顶部标签选择框与卡片标签均由本模块驱动，保证过滤维度一致、显示可读。
import type { ContentType, ContentLocale } from "./constants";

/** 单个标签的中英显示名（保留旧字段，兼容既有调用）。 */
export type TagLabel = { en: string; zh: string };

/** 单个标签的 10 语言显示名：en、zh-cn、pt-br、ru、de、es、fr、ja、ko、tr。 */
export type TagLabel10 = {
  en: string;
  "zh-cn": string;
  "pt-br": string;
  ru: string;
  de: string;
  es: string;
  fr: string;
  ja: string;
  ko: string;
  tr: string;
};

/** 一组标签（如「按职业」「按伤害」），values 为受控 slug，label 为该组的展示名。 */
export type TagFacet = { label: TagLabel; values: string[] };

/** 某分类的标签配置：facets 为选择框分组，labels 为所有 slug 的显示名。 */
export type CategoryTagConfig = {
  facets: TagFacet[];
  labels: Record<string, TagLabel>;
};

const DAMAGE_LABELS: Record<string, TagLabel> = {
  physical: { en: "Physical", zh: "物理" },
  fire: { en: "Fire", zh: "火焰" },
  cold: { en: "Cold", zh: "冰霜" },
  lightning: { en: "Lightning", zh: "闪电" },
  chaos: { en: "Chaos", zh: "混沌" },
  holy: { en: "Holy", zh: "神圣" },
  elemental: { en: "Elemental", zh: "元素" },
  poison: { en: "Poison", zh: "中毒" },
  bleed: { en: "Bleed", zh: "流血" },
  dot: { en: "DoT", zh: "持续伤害" },
};

/** 在统一的伤害标签基础上并入各分类专属标签，得到该分类完整的显示名词表。 */
function buildLabels(
  extra: Record<string, TagLabel>,
): Record<string, TagLabel> {
  return { ...DAMAGE_LABELS, ...extra };
}

export const TAG_TAXONOMY: Record<ContentType, CategoryTagConfig> = {
  boss: {
    facets: [
      {
        label: { en: "Campaign", zh: "剧情" },
        values: ["act-1", "act-2", "act-3", "act-4"],
      },
      {
        label: { en: "Encounter type", zh: "遭遇类型" },
        values: [
          "campaign",
          "optional",
          "trial",
          "endgame",
          "pinnacle",
          "permanent-reward",
        ],
      },
      {
        label: { en: "Damage", zh: "伤害" },
        values: [
          "physical",
          "fire",
          "cold",
          "lightning",
          "chaos",
          "holy",
          "elemental",
          "poison",
        ],
      },
      {
        label: { en: "Style", zh: "风格" },
        values: ["multi-phase", "sekhemas", "summoner", "arena", "boss-rush"],
      },
    ],
    labels: buildLabels({
      "act-1": { en: "Act 1", zh: "Act 1" },
      "act-2": { en: "Act 2", zh: "Act 2" },
      "act-3": { en: "Act 3", zh: "Act 3" },
      "act-4": { en: "Act 4", zh: "Act 4" },
      campaign: { en: "Campaign", zh: "剧情" },
      optional: { en: "Optional", zh: "可选" },
      trial: { en: "Trial", zh: "试炼" },
      endgame: { en: "Endgame", zh: "终局" },
      pinnacle: { en: "Pinnacle", zh: "巅峰" },
      "permanent-reward": { en: "Reward", zh: "奖励" },
      "multi-phase": { en: "Multi-phase", zh: "多阶段" },
      sekhemas: { en: "Sekhemas", zh: "Sekhemas" },
      summoner: { en: "Summoner", zh: "召唤" },
      arena: { en: "Arena", zh: "竞技场" },
      "boss-rush": { en: "Boss Rush", zh: "连续首领" },
      "map-boss": { en: "Map Boss", zh: "地图首领" },
    }),
  },
  build: {
    facets: [
      {
        label: { en: "Class", zh: "职业" },
        values: [
          "witch",
          "warrior",
          "ranger",
          "mercenary",
          "monk",
          "sorceress",
          "druid",
          "huntress",
        ],
      },
      {
        label: { en: "Stage", zh: "阶段" },
        values: ["starter", "leveling", "early-endgame", "endgame", "bossing"],
      },
      {
        label: { en: "Play style", zh: "玩法" },
        values: [
          "melee",
          "ranged",
          "caster",
          "minion",
          "dot",
          "trigger",
          "transformation",
          "mobile",
        ],
      },
      {
        label: { en: "Damage", zh: "伤害" },
        values: [
          "physical",
          "fire",
          "cold",
          "lightning",
          "chaos",
          "poison",
          "bleed",
          "elemental",
        ],
      },
    ],
    labels: buildLabels({
      witch: { en: "Witch", zh: "女巫" },
      warrior: { en: "Warrior", zh: "战士" },
      ranger: { en: "Ranger", zh: "游侠" },
      mercenary: { en: "Mercenary", zh: "雇佣兵" },
      monk: { en: "Monk", zh: "武僧" },
      sorceress: { en: "Sorceress", zh: "法师" },
      druid: { en: "Druid", zh: "德鲁伊" },
      huntress: { en: "Huntress", zh: "女猎手" },
      starter: { en: "Starter", zh: "开荒" },
      leveling: { en: "Leveling", zh: "练级" },
      "early-endgame": { en: "Early Endgame", zh: "前期终局" },
      endgame: { en: "Endgame", zh: "终局" },
      bossing: { en: "Bossing", zh: "打王" },
      melee: { en: "Melee", zh: "近战" },
      ranged: { en: "Ranged", zh: "远程" },
      caster: { en: "Caster", zh: "法术" },
      minion: { en: "Minion", zh: "召唤" },
      trigger: { en: "Trigger", zh: "触发" },
      transformation: { en: "Transformation", zh: "变身" },
      mobile: { en: "Mobile", zh: "机动" },
    }),
  },
  item: {
    facets: [
      {
        label: { en: "Category", zh: "类别" },
        values: [
          "weapons",
          "off-hand",
          "armour",
          "jewellery",
          "currency",
          "unique-items",
          "socketables",
          "unique-armour",
          "waystones",
          "charms",
          "uncut-gems",
        ],
      },
      {
        label: { en: "Mechanic", zh: "机制" },
        values: [
          "corruption",
          "vaal",
          "crafting",
          "upgrade",
          "high-risk",
          "trade",
          "unique",
        ],
      },
    ],
    labels: buildLabels({
      weapons: { en: "Weapons", zh: "武器" },
      "off-hand": { en: "Off-hand", zh: "副手" },
      armour: { en: "Armour", zh: "护甲" },
      jewellery: { en: "Jewellery", zh: "珠宝" },
      currency: { en: "Currency", zh: "通货" },
      "unique-items": { en: "Unique Items", zh: "独特物品" },
      socketables: { en: "Socketables", zh: "镶嵌物" },
      "unique-armour": { en: "Unique Armour", zh: "独特护甲" },
      waystones: { en: "Waystones", zh: "路石" },
      charms: { en: "Charms", zh: "护符" },
      "uncut-gems": { en: "Uncut Gems", zh: "未切割宝石" },
      corruption: { en: "Corruption", zh: "腐化" },
      vaal: { en: "Vaal", zh: "瓦尔" },
      crafting: { en: "Crafting", zh: "工艺" },
      upgrade: { en: "Upgrade", zh: "升级" },
      "high-risk": { en: "High Risk", zh: "高风险" },
      trade: { en: "Trade", zh: "交易" },
      unique: { en: "Unique", zh: "独特" },
    }),
  },
  skill: {
    facets: [
      {
        label: { en: "Category", zh: "类别" },
        values: [
          "active",
          "support",
          "spirit",
          "meta",
          "lineage",
          "ascendancy",
        ],
      },
      {
        label: { en: "Damage", zh: "伤害" },
        values: ["physical", "fire", "cold", "lightning", "chaos", "poison"],
      },
      {
        label: { en: "Use", zh: "用途" },
        values: [
          "damage",
          "defence",
          "mobility",
          "minions",
          "auras",
          "triggers",
        ],
      },
      {
        label: { en: "Delivery", zh: "形式" },
        values: ["projectile", "melee", "aoe", "bow", "spell"],
      },
    ],
    labels: buildLabels({
      active: { en: "Active", zh: "主动" },
      support: { en: "Support", zh: "辅助" },
      spirit: { en: "Spirit", zh: "灵魄" },
      meta: { en: "Meta", zh: "通用" },
      lineage: { en: "Lineage", zh: "血脉" },
      ascendancy: { en: "Ascendancy", zh: "升华" },
      defence: { en: "Defence", zh: "防御" },
      mobility: { en: "Mobility", zh: "机动" },
      minions: { en: "Minions", zh: "召唤物" },
      auras: { en: "Auras", zh: "光环" },
      triggers: { en: "Triggers", zh: "触发" },
      projectile: { en: "Projectile", zh: "弹射" },
      melee: { en: "Melee", zh: "近战" },
      aoe: { en: "AoE", zh: "范围" },
      bow: { en: "Bow", zh: "弓" },
      spell: { en: "Spell", zh: "法术" },
    }),
  },
  guide: {
    facets: [
      {
        label: { en: "Category", zh: "类别" },
        values: [
          "beginner",
          "campaign",
          "mechanics",
          "crafting-trading",
          "endgame-atlas",
          "troubleshooting",
        ],
      },
      {
        label: { en: "Topic", zh: "主题" },
        values: [
          "ascendancy",
          "passive",
          "currency",
          "map",
          "expedition",
          "trial",
          "league",
          "atlas",
          "crafting",
          "trading",
          "leveling",
          "endgame",
        ],
      },
    ],
    labels: buildLabels({
      beginner: { en: "Beginner", zh: "新手" },
      campaign: { en: "Campaign", zh: "剧情" },
      mechanics: { en: "Mechanics", zh: "机制" },
      "crafting-trading": { en: "Crafting & Trading", zh: "工艺与交易" },
      "endgame-atlas": { en: "Endgame & Atlas", zh: "终局与地图" },
      troubleshooting: { en: "Troubleshooting", zh: "排错" },
      ascendancy: { en: "Ascendancy", zh: "升华" },
      passive: { en: "Passive", zh: "天赋" },
      currency: { en: "Currency", zh: "通货" },
      map: { en: "Map", zh: "地图" },
      expedition: { en: "Expedition", zh: "远征" },
      trial: { en: "Trial", zh: "试炼" },
      league: { en: "League", zh: "赛季" },
      atlas: { en: "Atlas", zh: "地图" },
      crafting: { en: "Crafting", zh: "工艺" },
      trading: { en: "Trading", zh: "交易" },
      leveling: { en: "Leveling", zh: "练级" },
      endgame: { en: "Endgame", zh: "终局" },
    }),
  },
  patch: {
    facets: [
      {
        label: { en: "Release type", zh: "发布类型" },
        values: ["major-updates", "balance", "hotfixes", "bug-fixes"],
      },
      {
        label: { en: "Impact", zh: "影响" },
        values: [
          "builds",
          "bosses",
          "items",
          "skills",
          "atlas",
          "economy",
          "league",
          "balance",
        ],
      },
    ],
    labels: buildLabels({
      "major-updates": { en: "Major Updates", zh: "大版本" },
      balance: { en: "Balance", zh: "平衡" },
      hotfixes: { en: "Hotfixes", zh: "热修" },
      "bug-fixes": { en: "Bug Fixes", zh: "问题修复" },
      builds: { en: "Builds", zh: "流派" },
      bosses: { en: "Bosses", zh: "首领" },
      items: { en: "Items", zh: "物品" },
      skills: { en: "Skills", zh: "技能" },
      atlas: { en: "Atlas", zh: "地图" },
      economy: { en: "Economy", zh: "经济" },
      league: { en: "League", zh: "赛季" },
    }),
  },
};

/** build 分类的 10 语言显示名词表：覆盖全部职业/阶段/玩法/伤害 slug 及四个 facet 标题。 */
export const BUILD_TAG_LABELS_10: Record<string, TagLabel10> = {
  witch: {
    en: "Witch",
    "zh-cn": "女巫",
    "pt-br": "Bruxa",
    ru: "Ведьма",
    de: "Hexe",
    es: "Bruja",
    fr: "Sorcière",
    ja: "ウィッチ",
    ko: "위치",
    tr: "Cadı",
  },
  warrior: {
    en: "Warrior",
    "zh-cn": "战士",
    "pt-br": "Guerreiro",
    ru: "Воин",
    de: "Krieger",
    es: "Guerrero",
    fr: "Guerrier",
    ja: "ウォリアー",
    ko: "워리어",
    tr: "Savaşçı",
  },
  ranger: {
    en: "Ranger",
    "zh-cn": "游侠",
    "pt-br": "Caçador",
    ru: "Рейнджер",
    de: "Waldläufer",
    es: "Guardabosques",
    fr: "Rôdeur",
    ja: "レンジャー",
    ko: "레인저",
    tr: "Nişancı",
  },
  mercenary: {
    en: "Mercenary",
    "zh-cn": "雇佣兵",
    "pt-br": "Mercenário",
    ru: "Наемник",
    de: "Söldner",
    es: "Mercenario",
    fr: "Mercenaire",
    ja: "傭兵",
    ko: "용병",
    tr: "Paralı Asker",
  },
  monk: {
    en: "Monk",
    "zh-cn": "武僧",
    "pt-br": "Monge",
    ru: "Монах",
    de: "Mönch",
    es: "Monje",
    fr: "Moine",
    ja: "モンク",
    ko: "승려",
    tr: "Keşiş",
  },
  sorceress: {
    en: "Sorceress",
    "zh-cn": "法师",
    "pt-br": "Feiticeira",
    ru: "Чародейка",
    de: "Zauberin",
    es: "Hechicera",
    fr: "Sorcière",
    ja: "ソーセレス",
    ko: "소서리스",
    tr: "Büyücü",
  },
  druid: {
    en: "Druid",
    "zh-cn": "德鲁伊",
    "pt-br": "Druida",
    ru: "Друид",
    de: "Druide",
    es: "Druida",
    fr: "Druide",
    ja: "ドルイド",
    ko: "드루이드",
    tr: "Druid",
  },
  huntress: {
    en: "Huntress",
    "zh-cn": "女猎手",
    "pt-br": "Caçadora",
    ru: "Охотница",
    de: "Jägerin",
    es: "Cazadora",
    fr: "Chasseresse",
    ja: "ハントレス",
    ko: "헌트리스",
    tr: "Avcı",
  },
  starter: {
    en: "Starter",
    "zh-cn": "开荒",
    "pt-br": "Iniciante",
    ru: "Стартовый",
    de: "Starter",
    es: "Inicio",
    fr: "Débutant",
    ja: " starter",
    ko: "시작",
    tr: "Başlangıç",
  },
  leveling: {
    en: "Leveling",
    "zh-cn": "练级",
    "pt-br": "Nivelamento",
    ru: "Прокачка",
    de: "Leveln",
    es: "Subida de nivel",
    fr: "Montée de niveau",
    ja: "レベリング",
    ko: "레벨링",
    tr: "Seviye Atlama",
  },
  "early-endgame": {
    en: "Early Endgame",
    "zh-cn": "前期终局",
    "pt-br": "Início do Endgame",
    ru: "Ранний эндгейм",
    de: "Frühes Endgame",
    es: "Endgame inicial",
    fr: "Début de l'endgame",
    ja: "初期エンドゲーム",
    ko: "초반 엔드게임",
    tr: "Erken Endgame",
  },
  endgame: {
    en: "Endgame",
    "zh-cn": "终局",
    "pt-br": "Endgame",
    ru: "Эндгейм",
    de: "Endgame",
    es: "Endgame",
    fr: "Endgame",
    ja: "エンドゲーム",
    ko: "엔드게임",
    tr: "Endgame",
  },
  bossing: {
    en: "Bossing",
    "zh-cn": "打王",
    "pt-br": "Chefes",
    ru: "Боссинг",
    de: "Bosse",
    es: "Jefes",
    fr: "Boss",
    ja: "ボス戦",
    ko: "보스",
    tr: "Boss",
  },
  melee: {
    en: "Melee",
    "zh-cn": "近战",
    "pt-br": "Corpo a corpo",
    ru: "Ближний бой",
    de: "Nahkampf",
    es: "Cuerpo a cuerpo",
    fr: "Mêlée",
    ja: "近接",
    ko: "근접",
    tr: "Yakın Dövüş",
  },
  ranged: {
    en: "Ranged",
    "zh-cn": "远程",
    "pt-br": "À distância",
    ru: "Дальний бой",
    de: "Fernkampf",
    es: "A distancia",
    fr: "À distance",
    ja: "遠隔",
    ko: "원거리",
    tr: "Uzaktan",
  },
  caster: {
    en: "Caster",
    "zh-cn": "法术",
    "pt-br": "Lançador",
    ru: "Кастер",
    de: "Zauberer",
    es: "Lanzador",
    fr: "Lanceur",
    ja: "キャスター",
    ko: "캐스터",
    tr: "Büyücü",
  },
  minion: {
    en: "Minion",
    "zh-cn": "召唤",
    "pt-br": "Subordinado",
    ru: "Приспешник",
    de: "Untergebener",
    es: "Subordinado",
    fr: "Sbire",
    ja: "ミニオン",
    ko: "미니언",
    tr: "Minyon",
  },
  dot: {
    en: "DoT",
    "zh-cn": "持续伤害",
    "pt-br": "Dano ao longo do tempo",
    ru: "ДоТ",
    de: "Schaden über Zeit",
    es: "Daño por tiempo",
    fr: "Dégâts dans le temps",
    ja: "継続ダメージ",
    ko: "지속 피해",
    tr: "Sürekli Hasar",
  },
  trigger: {
    en: "Trigger",
    "zh-cn": "触发",
    "pt-br": "Gatilho",
    ru: "Триггер",
    de: "Auslöser",
    es: "Desencadenante",
    fr: "Déclencheur",
    ja: "トリガー",
    ko: "트리거",
    tr: "Tetikleyici",
  },
  transformation: {
    en: "Transformation",
    "zh-cn": "变身",
    "pt-br": "Transformação",
    ru: "Трансформация",
    de: "Verwandlung",
    es: "Transformación",
    fr: "Transformation",
    ja: "変身",
    ko: "변신",
    tr: "Dönüşüm",
  },
  mobile: {
    en: "Mobile",
    "zh-cn": "机动",
    "pt-br": "Móvel",
    ru: "Подвижный",
    de: "Beweglich",
    es: "Móvil",
    fr: "Mobile",
    ja: "機動",
    ko: "기동",
    tr: "Hareketli",
  },
  physical: {
    en: "Physical",
    "zh-cn": "物理",
    "pt-br": "Físico",
    ru: "Физический",
    de: "Physisch",
    es: "Físico",
    fr: "Physique",
    ja: "物理",
    ko: "물리",
    tr: "Fiziksel",
  },
  fire: {
    en: "Fire",
    "zh-cn": "火焰",
    "pt-br": "Fogo",
    ru: "Огонь",
    de: "Feuer",
    es: "Fuego",
    fr: "Feu",
    ja: "火",
    ko: "화염",
    tr: "Ateş",
  },
  cold: {
    en: "Cold",
    "zh-cn": "冰霜",
    "pt-br": "Frio",
    ru: "Холод",
    de: "Kälte",
    es: "Frío",
    fr: "Froid",
    ja: "冷気",
    ko: "냉기",
    tr: "Soğuk",
  },
  lightning: {
    en: "Lightning",
    "zh-cn": "闪电",
    "pt-br": "Raio",
    ru: "Молния",
    de: "Blitz",
    es: "Relámpago",
    fr: "Éclair",
    ja: "雷",
    ko: "번개",
    tr: "Yıldırım",
  },
  chaos: {
    en: "Chaos",
    "zh-cn": "混沌",
    "pt-br": "Caos",
    ru: "Хаос",
    de: "Chaos",
    es: "Caos",
    fr: "Chaos",
    ja: "カオス",
    ko: "혼돈",
    tr: "Kaos",
  },
  poison: {
    en: "Poison",
    "zh-cn": "中毒",
    "pt-br": "Veneno",
    ru: "Яд",
    de: "Gift",
    es: "Veneno",
    fr: "Poison",
    ja: "毒",
    ko: "독",
    tr: "Zehir",
  },
  bleed: {
    en: "Bleed",
    "zh-cn": "流血",
    "pt-br": "Sangramento",
    ru: "Кровотечение",
    de: "Bluten",
    es: "Sangrado",
    fr: "Saignement",
    ja: "出血",
    ko: "출혈",
    tr: "Kanama",
  },
  elemental: {
    en: "Elemental",
    "zh-cn": "元素",
    "pt-br": "Elemental",
    ru: "Стихийный",
    de: "Elementar",
    es: "Elemental",
    fr: "Élémentaire",
    ja: "エレメンタル",
    ko: "속성",
    tr: "Elementel",
  },
  Class: {
    en: "Class",
    "zh-cn": "职业",
    "pt-br": "Classe",
    ru: "Класс",
    de: "Klasse",
    es: "Clase",
    fr: "Classe",
    ja: "クラス",
    ko: "직업",
    tr: "Sınıf",
  },
  Stage: {
    en: "Stage",
    "zh-cn": "阶段",
    "pt-br": "Fase",
    ru: "Этап",
    de: "Phase",
    es: "Etapa",
    fr: "Étape",
    ja: "ステージ",
    ko: "단계",
    tr: "Aşama",
  },
  "Play style": {
    en: "Play style",
    "zh-cn": "玩法",
    "pt-br": "Estilo de jogo",
    ru: "Стиль игры",
    de: "Spielstil",
    es: "Estilo de juego",
    fr: "Style de jeu",
    ja: "プレイスタイル",
    ko: "플레이 스타일",
    tr: "Oyun Tarzı",
  },
  Damage: {
    en: "Damage",
    "zh-cn": "伤害",
    "pt-br": "Dano",
    ru: "Урон",
    de: "Schaden",
    es: "Daño",
    fr: "Dégâts",
    ja: "ダメージ",
    ko: "피해",
    tr: "Hasar",
  },
};

/** guide 分类的 10 语言显示名词表：覆盖 Category、Topic 标题及全部 guide facets 值。 */
export const GUIDE_TAG_LABELS_10: Record<string, TagLabel10> = {
  beginner: {
    en: "Beginner",
    "zh-cn": "新手",
    "pt-br": "Iniciante",
    ru: "Новичок",
    de: "Anfänger",
    es: "Principiante",
    fr: "Débutant",
    ja: "初心者",
    ko: "초보",
    tr: "Başlangıç",
  },
  campaign: {
    en: "Campaign",
    "zh-cn": "剧情",
    "pt-br": "Campanha",
    ru: "Кампания",
    de: "Kampagne",
    es: "Campaña",
    fr: "Campagne",
    ja: "キャンペーン",
    ko: "캠페인",
    tr: "Kampanya",
  },
  mechanics: {
    en: "Mechanics",
    "zh-cn": "机制",
    "pt-br": "Mecânica",
    ru: "Механика",
    de: "Mechanik",
    es: "Mecánica",
    fr: "Mécanique",
    ja: "メカニクス",
    ko: "메커니즘",
    tr: "Mekanik",
  },
  "crafting-trading": {
    en: "Crafting & Trading",
    "zh-cn": "工艺与交易",
    "pt-br": "Crafting e Comércio",
    ru: "Крафт и торговля",
    de: "Crafting & Handel",
    es: "Crafting y Comercio",
    fr: "Artisanat et Commerce",
    ja: "クラフトと取引",
    ko: "제작과 거래",
    tr: "Üretim ve Ticaret",
  },
  "endgame-atlas": {
    en: "Endgame & Atlas",
    "zh-cn": "终局与地图",
    "pt-br": "Endgame e Atlas",
    ru: "Эндгейм и Атлас",
    de: "Endgame & Atlas",
    es: "Endgame y Atlas",
    fr: "Endgame et Atlas",
    ja: "エンドゲームとアトラス",
    ko: "엔드게임과 지도",
    tr: "Endgame ve Atlas",
  },
  troubleshooting: {
    en: "Troubleshooting",
    "zh-cn": "排错",
    "pt-br": "Solução de Problemas",
    ru: "Устранение неполадок",
    de: "Fehlerbehebung",
    es: "Solución de Problemas",
    fr: "Dépannage",
    ja: "トラブルシューティング",
    ko: "문제 해결",
    tr: "Sorun Giderme",
  },
  ascendancy: {
    en: "Ascendancy",
    "zh-cn": "升华",
    "pt-br": "Ascendência",
    ru: "Вознесение",
    de: "Aufstieg",
    es: "Ascendencia",
    fr: "Ascendance",
    ja: "アセンダンシー",
    ko: "승천",
    tr: "Yükseliş",
  },
  passive: {
    en: "Passive",
    "zh-cn": "天赋",
    "pt-br": "Passiva",
    ru: "Пассивная",
    de: "Passiv",
    es: "Pasiva",
    fr: "Passif",
    ja: "パッシブ",
    ko: "패시브",
    tr: "Pasif",
  },
  currency: {
    en: "Currency",
    "zh-cn": "通货",
    "pt-br": "Moeda",
    ru: "Валюта",
    de: "Währung",
    es: "Divisa",
    fr: "Monnaie",
    ja: "通貨",
    ko: "화폐",
    tr: "Para",
  },
  map: {
    en: "Map",
    "zh-cn": "地图",
    "pt-br": "Mapa",
    ru: "Карта",
    de: "Karte",
    es: "Mapa",
    fr: "Carte",
    ja: "マップ",
    ko: "지도",
    tr: "Harita",
  },
  expedition: {
    en: "Expedition",
    "zh-cn": "远征",
    "pt-br": "Expedição",
    ru: "Экспедиция",
    de: "Expedition",
    es: "Expedición",
    fr: "Expédition",
    ja: "エクスペディション",
    ko: "원정",
    tr: "Seferi",
  },
  trial: {
    en: "Trial",
    "zh-cn": "试炼",
    "pt-br": "Provação",
    ru: "Испытание",
    de: "Prüfung",
    es: "Prueba",
    fr: "Épreuve",
    ja: "試練",
    ko: "시련",
    tr: "Deneme",
  },
  league: {
    en: "League",
    "zh-cn": "赛季",
    "pt-br": "Liga",
    ru: "Лига",
    de: "Liga",
    es: "Liga",
    fr: "Ligue",
    ja: "リーグ",
    ko: "리그",
    tr: "Lig",
  },
  atlas: {
    en: "Atlas",
    "zh-cn": "地图",
    "pt-br": "Atlas",
    ru: "Атлас",
    de: "Atlas",
    es: "Atlas",
    fr: "Atlas",
    ja: "アトラス",
    ko: "아틀라스",
    tr: "Atlas",
  },
  crafting: {
    en: "Crafting",
    "zh-cn": "工艺",
    "pt-br": "Fabricação",
    ru: "Создание",
    de: "Herstellung",
    es: "Fabricación",
    fr: "Artisanat",
    ja: "クラフト",
    ko: "제작",
    tr: "Üretim",
  },
  trading: {
    en: "Trading",
    "zh-cn": "交易",
    "pt-br": "Comércio",
    ru: "Торговля",
    de: "Handel",
    es: "Comercio",
    fr: "Commerce",
    ja: "取引",
    ko: "거래",
    tr: "Ticaret",
  },
  leveling: {
    en: "Leveling",
    "zh-cn": "练级",
    "pt-br": "Nivelamento",
    ru: "Прокачка",
    de: "Leveln",
    es: "Subida de nivel",
    fr: "Montée de niveau",
    ja: "レベリング",
    ko: "레벨링",
    tr: "Seviye Atlama",
  },
  endgame: {
    en: "Endgame",
    "zh-cn": "终局",
    "pt-br": "Endgame",
    ru: "Эндгейм",
    de: "Endgame",
    es: "Endgame",
    fr: "Endgame",
    ja: "エンドゲーム",
    ko: "엔드게임",
    tr: "Endgame",
  },
  Category: {
    en: "Category",
    "zh-cn": "类别",
    "pt-br": "Categoria",
    ru: "Категория",
    de: "Kategorie",
    es: "Categoría",
    fr: "Catégorie",
    ja: "カテゴリ",
    ko: "분류",
    tr: "Kategori",
  },
  Topic: {
    en: "Topic",
    "zh-cn": "主题",
    "pt-br": "Tópico",
    ru: "Тема",
    de: "Thema",
    es: "Tema",
    fr: "Sujet",
    ja: "トピック",
    ko: "주제",
    tr: "Konu",
  },
};

/** boss 分类的 10 语言显示名词表：覆盖全部 boss facets 值及四个 facet 标题。 */
export const BOSS_TAG_LABELS_10: Record<string, TagLabel10> = {
  "act-1": {
    en: "Act 1",
    "zh-cn": "第一幕",
    "pt-br": "Ato 1",
    ru: "Акт 1",
    de: "Akt 1",
    es: "Acto 1",
    fr: "Acte 1",
    ja: "Act 1",
    ko: "1막",
    tr: "Bölüm 1",
  },
  "act-2": {
    en: "Act 2",
    "zh-cn": "第二幕",
    "pt-br": "Ato 2",
    ru: "Акт 2",
    de: "Akt 2",
    es: "Acto 2",
    fr: "Acte 2",
    ja: "Act 2",
    ko: "2막",
    tr: "Bölüm 2",
  },
  "act-3": {
    en: "Act 3",
    "zh-cn": "第三幕",
    "pt-br": "Ato 3",
    ru: "Акт 3",
    de: "Akt 3",
    es: "Acto 3",
    fr: "Acte 3",
    ja: "Act 3",
    ko: "3막",
    tr: "Bölüm 3",
  },
  "act-4": {
    en: "Act 4",
    "zh-cn": "第四幕",
    "pt-br": "Ato 4",
    ru: "Акт 4",
    de: "Akt 4",
    es: "Acto 4",
    fr: "Acte 4",
    ja: "Act 4",
    ko: "4막",
    tr: "Bölüm 4",
  },
  campaign: {
    en: "Campaign",
    "zh-cn": "剧情",
    "pt-br": "Campanha",
    ru: "Кампания",
    de: "Kampagne",
    es: "Campaña",
    fr: "Campagne",
    ja: "キャンペーン",
    ko: "캠페인",
    tr: "Kampanya",
  },
  optional: {
    en: "Optional",
    "zh-cn": "可选",
    "pt-br": "Opcional",
    ru: "Дополнительный",
    de: "Optional",
    es: "Opcional",
    fr: "Optionnel",
    ja: "オプション",
    ko: "선택",
    tr: "İsteğe Bağlı",
  },
  trial: {
    en: "Trial",
    "zh-cn": "试炼",
    "pt-br": "Provação",
    ru: "Испытание",
    de: "Prüfung",
    es: "Prueba",
    fr: "Épreuve",
    ja: "試練",
    ko: "시련",
    tr: "Deneme",
  },
  endgame: {
    en: "Endgame",
    "zh-cn": "终局",
    "pt-br": "Endgame",
    ru: "Эндгейм",
    de: "Endgame",
    es: "Endgame",
    fr: "Endgame",
    ja: "エンドゲーム",
    ko: "엔드게임",
    tr: "Endgame",
  },
  pinnacle: {
    en: "Pinnacle",
    "zh-cn": "巅峰",
    "pt-br": "Ápice",
    ru: "Пик",
    de: "Gipfel",
    es: "Cúspide",
    fr: "Sommet",
    ja: "頂点",
    ko: "정점",
    tr: "Zirve",
  },
  "permanent-reward": {
    en: "Reward",
    "zh-cn": "奖励",
    "pt-br": "Recompensa",
    ru: "Награда",
    de: "Belohnung",
    es: "Recompensa",
    fr: "Récompense",
    ja: "報酬",
    ko: "보상",
    tr: "Ödül",
  },
  physical: {
    en: "Physical",
    "zh-cn": "物理",
    "pt-br": "Físico",
    ru: "Физический",
    de: "Physisch",
    es: "Físico",
    fr: "Physique",
    ja: "物理",
    ko: "물리",
    tr: "Fiziksel",
  },
  fire: {
    en: "Fire",
    "zh-cn": "火焰",
    "pt-br": "Fogo",
    ru: "Огонь",
    de: "Feuer",
    es: "Fuego",
    fr: "Feu",
    ja: "火",
    ko: "화염",
    tr: "Ateş",
  },
  cold: {
    en: "Cold",
    "zh-cn": "冰霜",
    "pt-br": "Frio",
    ru: "Холод",
    de: "Kälte",
    es: "Frío",
    fr: "Froid",
    ja: "冷気",
    ko: "냉기",
    tr: "Soğuk",
  },
  lightning: {
    en: "Lightning",
    "zh-cn": "闪电",
    "pt-br": "Raio",
    ru: "Молния",
    de: "Blitz",
    es: "Relámpago",
    fr: "Éclair",
    ja: "雷",
    ko: "번개",
    tr: "Yıldırım",
  },
  chaos: {
    en: "Chaos",
    "zh-cn": "混沌",
    "pt-br": "Caos",
    ru: "Хаос",
    de: "Chaos",
    es: "Caos",
    fr: "Chaos",
    ja: "カオス",
    ko: "혼돈",
    tr: "Kaos",
  },
  holy: {
    en: "Holy",
    "zh-cn": "神圣",
    "pt-br": "Sagrado",
    ru: "Святой",
    de: "Heilig",
    es: "Sagrado",
    fr: "Saint",
    ja: "聖",
    ko: "성스러운",
    tr: "Kutsal",
  },
  elemental: {
    en: "Elemental",
    "zh-cn": "元素",
    "pt-br": "Elemental",
    ru: "Стихийный",
    de: "Elementar",
    es: "Elemental",
    fr: "Élémentaire",
    ja: "エレメンタル",
    ko: "속성",
    tr: "Elementel",
  },
  poison: {
    en: "Poison",
    "zh-cn": "中毒",
    "pt-br": "Veneno",
    ru: "Яд",
    de: "Gift",
    es: "Veneno",
    fr: "Poison",
    ja: "毒",
    ko: "독",
    tr: "Zehir",
  },
  "multi-phase": {
    en: "Multi-phase",
    "zh-cn": "多阶段",
    "pt-br": "Multifase",
    ru: "Многофазный",
    de: "Mehrphasig",
    es: "Multifase",
    fr: "Multiphase",
    ja: "マルチフェーズ",
    ko: "다단계",
    tr: "Çok Aşamalı",
  },
  sekhemas: {
    en: "Sekhemas",
    "zh-cn": "Sekhemas",
    "pt-br": "Sekhemas",
    ru: "Секхемас",
    de: "Sekhemas",
    es: "Sekhemas",
    fr: "Sekhemas",
    ja: "セケマス",
    ko: "세케마스",
    tr: "Sekhemas",
  },
  summoner: {
    en: "Summoner",
    "zh-cn": "召唤",
    "pt-br": "Invocador",
    ru: "Призыватель",
    de: "Beschwörer",
    es: "Invocador",
    fr: "Invocateur",
    ja: "サモナー",
    ko: "소환사",
    tr: "Çağrıcı",
  },
  arena: {
    en: "Arena",
    "zh-cn": "竞技场",
    "pt-br": "Arena",
    ru: "Арена",
    de: "Arena",
    es: "Arena",
    fr: "Arène",
    ja: "アリーナ",
    ko: "투기장",
    tr: "Arena",
  },
  "boss-rush": {
    en: "Boss Rush",
    "zh-cn": "连续首领",
    "pt-br": "Corrida de Chefes",
    ru: "Раш боссов",
    de: "Boss-Rush",
    es: "Carrera de Jefes",
    fr: "Ruée de Boss",
    ja: "ボスラッシュ",
    ko: "보스 러시",
    tr: "Boss Akını",
  },
  Campaign: {
    en: "Campaign",
    "zh-cn": "剧情",
    "pt-br": "Campanha",
    ru: "Кампания",
    de: "Kampagne",
    es: "Campaña",
    fr: "Campagne",
    ja: "キャンペーン",
    ko: "캠페인",
    tr: "Kampanya",
  },
  "Encounter type": {
    en: "Encounter type",
    "zh-cn": "遭遇类型",
    "pt-br": "Tipo de encontro",
    ru: "Тип встречи",
    de: "Begegnungstyp",
    es: "Tipo de encuentro",
    fr: "Type de rencontre",
    ja: "エンカウンタータイプ",
    ko: "조우 유형",
    tr: "Karşılaşma Türü",
  },
  Damage: {
    en: "Damage",
    "zh-cn": "伤害",
    "pt-br": "Dano",
    ru: "Урон",
    de: "Schaden",
    es: "Daño",
    fr: "Dégâts",
    ja: "ダメージ",
    ko: "피해",
    tr: "Hasar",
  },
  Style: {
    en: "Style",
    "zh-cn": "风格",
    "pt-br": "Estilo",
    ru: "Стиль",
    de: "Stil",
    es: "Estilo",
    fr: "Style",
    ja: "スタイル",
    ko: "스타일",
    tr: "Tarz",
  },
};

/** skill 分类的 10 语言显示名词表：覆盖全部 skill facets 值及四个 facet 标题。 */
export const SKILL_TAG_LABELS_10: Record<string, TagLabel10> = {
  active: {
    en: "Active",
    "zh-cn": "主动",
    "pt-br": "Ativa",
    ru: "Активный",
    de: "Aktiv",
    es: "Activa",
    fr: "Active",
    ja: "アクティブ",
    ko: "액티브",
    tr: "Aktif",
  },
  support: {
    en: "Support",
    "zh-cn": "辅助",
    "pt-br": "Suporte",
    ru: "Поддержка",
    de: "Unterstützung",
    es: "Soporte",
    fr: "Soutien",
    ja: "サポート",
    ko: "서포트",
    tr: "Destek",
  },
  spirit: {
    en: "Spirit",
    "zh-cn": "灵魄",
    "pt-br": "Espírito",
    ru: "Дух",
    de: "Geist",
    es: "Espíritu",
    fr: "Esprit",
    ja: "スピリット",
    ko: "정신",
    tr: "Ruh",
  },
  meta: {
    en: "Meta",
    "zh-cn": "通用",
    "pt-br": "Meta",
    ru: "Мета",
    de: "Meta",
    es: "Meta",
    fr: "Méta",
    ja: "メタ",
    ko: "메타",
    tr: "Meta",
  },
  lineage: {
    en: "Lineage",
    "zh-cn": "血脉",
    "pt-br": "Linhagem",
    ru: "Родословная",
    de: "Abstammung",
    es: "Linaje",
    fr: "Lignage",
    ja: "系統",
    ko: "혈통",
    tr: "Soy",
  },
  ascendancy: {
    en: "Ascendancy",
    "zh-cn": "升华",
    "pt-br": "Ascendência",
    ru: "Вознесение",
    de: "Aufstieg",
    es: "Ascendencia",
    fr: "Ascendance",
    ja: "アセンダンシー",
    ko: "승천",
    tr: "Yükseliş",
  },
  physical: {
    en: "Physical",
    "zh-cn": "物理",
    "pt-br": "Físico",
    ru: "Физический",
    de: "Physisch",
    es: "Físico",
    fr: "Physique",
    ja: "物理",
    ko: "물리",
    tr: "Fiziksel",
  },
  fire: {
    en: "Fire",
    "zh-cn": "火焰",
    "pt-br": "Fogo",
    ru: "Огонь",
    de: "Feuer",
    es: "Fuego",
    fr: "Feu",
    ja: "火",
    ko: "화염",
    tr: "Ateş",
  },
  cold: {
    en: "Cold",
    "zh-cn": "冰霜",
    "pt-br": "Frio",
    ru: "Холод",
    de: "Kälte",
    es: "Frío",
    fr: "Froid",
    ja: "冷気",
    ko: "냉기",
    tr: "Soğuk",
  },
  lightning: {
    en: "Lightning",
    "zh-cn": "闪电",
    "pt-br": "Raio",
    ru: "Молния",
    de: "Blitz",
    es: "Relámpago",
    fr: "Éclair",
    ja: "雷",
    ko: "번개",
    tr: "Yıldırım",
  },
  chaos: {
    en: "Chaos",
    "zh-cn": "混沌",
    "pt-br": "Caos",
    ru: "Хаос",
    de: "Chaos",
    es: "Caos",
    fr: "Chaos",
    ja: "カオス",
    ko: "혼돈",
    tr: "Kaos",
  },
  poison: {
    en: "Poison",
    "zh-cn": "中毒",
    "pt-br": "Veneno",
    ru: "Яд",
    de: "Gift",
    es: "Veneno",
    fr: "Poison",
    ja: "毒",
    ko: "독",
    tr: "Zehir",
  },
  damage: {
    en: "Damage",
    "zh-cn": "伤害",
    "pt-br": "Dano",
    ru: "Урон",
    de: "Schaden",
    es: "Daño",
    fr: "Dégâts",
    ja: "ダメージ",
    ko: "피해",
    tr: "Hasar",
  },
  defence: {
    en: "Defence",
    "zh-cn": "防御",
    "pt-br": "Defesa",
    ru: "Защита",
    de: "Verteidigung",
    es: "Defensa",
    fr: "Défense",
    ja: "防御",
    ko: "방어",
    tr: "Savunma",
  },
  mobility: {
    en: "Mobility",
    "zh-cn": "机动",
    "pt-br": "Mobilidade",
    ru: "Подвижность",
    de: "Beweglichkeit",
    es: "Movilidad",
    fr: "Mobilité",
    ja: "機動",
    ko: "기동",
    tr: "Hareketlilik",
  },
  minions: {
    en: "Minions",
    "zh-cn": "召唤物",
    "pt-br": "Subordinados",
    ru: "Приспешники",
    de: "Untergebene",
    es: "Subordinados",
    fr: "Sbires",
    ja: "ミニオン",
    ko: "미니언",
    tr: "Minyonlar",
  },
  auras: {
    en: "Auras",
    "zh-cn": "光环",
    "pt-br": "Auras",
    ru: "Ауры",
    de: "Auren",
    es: "Auras",
    fr: "Auras",
    ja: "オーラ",
    ko: "오라",
    tr: "Auralar",
  },
  triggers: {
    en: "Triggers",
    "zh-cn": "触发",
    "pt-br": "Gatilhos",
    ru: "Триггеры",
    de: "Auslöser",
    es: "Desencadenantes",
    fr: "Déclencheurs",
    ja: "トリガー",
    ko: "트리거",
    tr: "Tetikleyiciler",
  },
  projectile: {
    en: "Projectile",
    "zh-cn": "弹射",
    "pt-br": "Projétil",
    ru: "Снаряд",
    de: "Geschoss",
    es: "Proyectil",
    fr: "Projectile",
    ja: "投射",
    ko: "투사체",
    tr: "Mermi",
  },
  melee: {
    en: "Melee",
    "zh-cn": "近战",
    "pt-br": "Corpo a corpo",
    ru: "Ближний бой",
    de: "Nahkampf",
    es: "Cuerpo a cuerpo",
    fr: "Mêlée",
    ja: "近接",
    ko: "근접",
    tr: "Yakın Dövüş",
  },
  aoe: {
    en: "AoE",
    "zh-cn": "范围",
    "pt-br": "Área",
    ru: "Область",
    de: "Fläche",
    es: "Área",
    fr: "Zone",
    ja: "範囲",
    ko: "범위",
    tr: "Alan",
  },
  bow: {
    en: "Bow",
    "zh-cn": "弓",
    "pt-br": "Arco",
    ru: "Лук",
    de: "Bogen",
    es: "Arco",
    fr: "Arc",
    ja: "弓",
    ko: "활",
    tr: "Yay",
  },
  spell: {
    en: "Spell",
    "zh-cn": "法术",
    "pt-br": "Magia",
    ru: "Заклинание",
    de: "Zauber",
    es: "Hechizo",
    fr: "Sort",
    ja: "スペル",
    ko: "스펠",
    tr: "Büyü",
  },
  Category: {
    en: "Category",
    "zh-cn": "类别",
    "pt-br": "Categoria",
    ru: "Категория",
    de: "Kategorie",
    es: "Categoría",
    fr: "Catégorie",
    ja: "カテゴリ",
    ko: "분류",
    tr: "Kategori",
  },
  Damage: {
    en: "Damage",
    "zh-cn": "伤害",
    "pt-br": "Dano",
    ru: "Урон",
    de: "Schaden",
    es: "Daño",
    fr: "Dégâts",
    ja: "ダメージ",
    ko: "피해",
    tr: "Hasar",
  },
  Use: {
    en: "Use",
    "zh-cn": "用途",
    "pt-br": "Uso",
    ru: "Применение",
    de: "Verwendung",
    es: "Uso",
    fr: "Utilisation",
    ja: "用途",
    ko: "용도",
    tr: "Kullanım",
  },
  Delivery: {
    en: "Delivery",
    "zh-cn": "形式",
    "pt-br": "Forma",
    ru: "Форма",
    de: "Art",
    es: "Forma",
    fr: "Forme",
    ja: "形式",
    ko: "형태",
    tr: "Biçim",
  },
};

/** item 分类的 10 语言显示名词表：覆盖全部 item facets 值及两个 facet 标题。 */
export const ITEM_TAG_LABELS_10: Record<string, TagLabel10> = {
  weapons: {
    en: "Weapons",
    "zh-cn": "武器",
    "pt-br": "Armas",
    ru: "Оружие",
    de: "Waffen",
    es: "Armas",
    fr: "Armes",
    ja: "武器",
    ko: "무기",
    tr: "Silahlar",
  },
  "off-hand": {
    en: "Off-hand",
    "zh-cn": "副手",
    "pt-br": "Mão secundária",
    ru: "Второе оружие",
    de: "Nebenhand",
    es: "Mano secundaria",
    fr: "Main secondaire",
    ja: "オフハンド",
    ko: "보조 무기",
    tr: "Yan El",
  },
  armour: {
    en: "Armour",
    "zh-cn": "护甲",
    "pt-br": "Armadura",
    ru: "Броня",
    de: "Rüstung",
    es: "Armadura",
    fr: "Armure",
    ja: "防具",
    ko: "갑옷",
    tr: "Zırh",
  },
  jewellery: {
    en: "Jewellery",
    "zh-cn": "珠宝",
    "pt-br": "Joias",
    ru: "Украшения",
    de: "Schmuck",
    es: "Joyería",
    fr: "Bijouterie",
    ja: "ジュエリー",
    ko: "장신구",
    tr: "Mücevher",
  },
  currency: {
    en: "Currency",
    "zh-cn": "通货",
    "pt-br": "Moeda",
    ru: "Валюта",
    de: "Währung",
    es: "Divisa",
    fr: "Monnaie",
    ja: "通貨",
    ko: "화폐",
    tr: "Para",
  },
  "unique-items": {
    en: "Unique Items",
    "zh-cn": "独特物品",
    "pt-br": "Itens Únicos",
    ru: "Уникальные предметы",
    de: "Einzigartige Gegenstände",
    es: "Objetos Únicos",
    fr: "Objets Uniques",
    ja: "ユニークアイテム",
    ko: "고유 아이템",
    tr: "Nadir Eşyalar",
  },
  socketables: {
    en: "Socketables",
    "zh-cn": "镶嵌物",
    "pt-br": "Encaixáveis",
    ru: "Вставки",
    de: "Einlegbare",
    es: "Encajables",
    fr: "Enchâssables",
    ja: "ソケット品",
    ko: "소켓 가능 아이템",
    tr: "Yuvalanabilir",
  },
  "unique-armour": {
    en: "Unique Armour",
    "zh-cn": "独特护甲",
    "pt-br": "Armadura Única",
    ru: "Уникальная броня",
    de: "Einzigartige Rüstung",
    es: "Armadura Única",
    fr: "Armure Unique",
    ja: "ユニーク防具",
    ko: "고유 갑옷",
    tr: "Nadir Zırh",
  },
  waystones: {
    en: "Waystones",
    "zh-cn": "路石",
    "pt-br": "Pedras de Caminho",
    ru: "Камни пути",
    de: "Wegsteine",
    es: "Piedras de Sendero",
    fr: "Pierres de Chemin",
    ja: "ウェイストーン",
    ko: "길돌",
    tr: "Yol Taşları",
  },
  charms: {
    en: "Charms",
    "zh-cn": "护符",
    "pt-br": "Amuletos",
    ru: "Амулеты",
    de: "Amuletten",
    es: "Amuletos",
    fr: "Charmes",
    ja: "チャーム",
    ko: "부적",
    tr: "Muskalar",
  },
  "uncut-gems": {
    en: "Uncut Gems",
    "zh-cn": "未切割宝石",
    "pt-br": "Gemas Não Lapidadas",
    ru: "Неогранённые камни",
    de: "Ungefasste Edelsteine",
    es: "Gemas sin tallar",
    fr: "Gemmes Brutes",
    ja: "未加工ジェム",
    ko: "가공되지 않은 보석",
    tr: "Kesilmemiş Mücevherler",
  },
  corruption: {
    en: "Corruption",
    "zh-cn": "腐化",
    "pt-br": "Corrupção",
    ru: "Порча",
    de: "Verderbnis",
    es: "Corrupción",
    fr: "Corruption",
    ja: "腐敗",
    ko: "타락",
    tr: "Yozlaşma",
  },
  vaal: {
    en: "Vaal",
    "zh-cn": "瓦尔",
    "pt-br": "Vaal",
    ru: "Ваал",
    de: "Vaal",
    es: "Vaal",
    fr: "Vaal",
    ja: "ヴァール",
    ko: "바알",
    tr: "Vaal",
  },
  crafting: {
    en: "Crafting",
    "zh-cn": "工艺",
    "pt-br": "Fabricação",
    ru: "Создание",
    de: "Herstellung",
    es: "Fabricación",
    fr: "Artisanat",
    ja: "クラフト",
    ko: "제작",
    tr: "Üretim",
  },
  upgrade: {
    en: "Upgrade",
    "zh-cn": "升级",
    "pt-br": "Aprimoramento",
    ru: "Улучшение",
    de: "Verbesserung",
    es: "Mejora",
    fr: "Amélioration",
    ja: "アップグレード",
    ko: "강화",
    tr: "Yükseltme",
  },
  "high-risk": {
    en: "High Risk",
    "zh-cn": "高风险",
    "pt-br": "Alto Risco",
    ru: "Высокий риск",
    de: "Hohes Risiko",
    es: "Alto Riesgo",
    fr: "Haut Risque",
    ja: "高リスク",
    ko: "고위험",
    tr: "Yüksek Risk",
  },
  trade: {
    en: "Trade",
    "zh-cn": "交易",
    "pt-br": "Comércio",
    ru: "Торговля",
    de: "Handel",
    es: "Comercio",
    fr: "Commerce",
    ja: "取引",
    ko: "거래",
    tr: "Ticaret",
  },
  unique: {
    en: "Unique",
    "zh-cn": "独特",
    "pt-br": "Único",
    ru: "Уникальный",
    de: "Einzigartig",
    es: "Único",
    fr: "Unique",
    ja: "ユニーク",
    ko: "고유",
    tr: "Nadir",
  },
  Category: {
    en: "Category",
    "zh-cn": "类别",
    "pt-br": "Categoria",
    ru: "Категория",
    de: "Kategorie",
    es: "Categoría",
    fr: "Catégorie",
    ja: "カテゴリ",
    ko: "분류",
    tr: "Kategori",
  },
  Mechanic: {
    en: "Mechanic",
    "zh-cn": "机制",
    "pt-br": "Mecânica",
    ru: "Механика",
    de: "Mechanik",
    es: "Mecánica",
    fr: "Mécanique",
    ja: "メカニック",
    ko: "메커니즘",
    tr: "Mekanik",
  },
};

/** patch 分类的 10 语言显示名词表：覆盖 Release type、Impact 标题及全部 patch facets 值。 */
export const PATCH_TAG_LABELS_10: Record<string, TagLabel10> = {
  "major-updates": {
    en: "Major Updates",
    "zh-cn": "大版本",
    "pt-br": "Atualizações Principais",
    ru: "Крупные обновления",
    de: "Große Updates",
    es: "Actualizaciones Principales",
    fr: "Mises à jour Majeures",
    ja: "メジャーアップデート",
    ko: "대형 업데이트",
    tr: "Büyük Güncellemeler",
  },
  balance: {
    en: "Balance",
    "zh-cn": "平衡",
    "pt-br": "Equilíbrio",
    ru: "Баланс",
    de: "Balance",
    es: "Equilibrio",
    fr: "Équilibrage",
    ja: "バランス",
    ko: "밸런스",
    tr: "Denge",
  },
  hotfixes: {
    en: "Hotfixes",
    "zh-cn": "热修",
    "pt-br": "Correções Rápidas",
    ru: "Горячие исправления",
    de: "Hotfixes",
    es: "Parches Rápidos",
    fr: "Correctifs",
    ja: "ホットフィックス",
    ko: "핫픽스",
    tr: "Acil Düzeltmeler",
  },
  "bug-fixes": {
    en: "Bug Fixes",
    "zh-cn": "问题修复",
    "pt-br": "Correções de Erros",
    ru: "Исправления ошибок",
    de: "Fehlerbehebungen",
    es: "Corrección de Errores",
    fr: "Corrections de Bugs",
    ja: "バグ修正",
    ko: "버그 수정",
    tr: "Hata Düzeltmeleri",
  },
  builds: {
    en: "Builds",
    "zh-cn": "流派",
    "pt-br": "Builds",
    ru: "Билды",
    de: "Builds",
    es: "Builds",
    fr: "Builds",
    ja: "ビルド",
    ko: "빌드",
    tr: "Yapılar",
  },
  bosses: {
    en: "Bosses",
    "zh-cn": "首领",
    "pt-br": "Chefes",
    ru: "Боссы",
    de: "Bosse",
    es: "Jefes",
    fr: "boss",
    ja: "ボス",
    ko: "보스",
    tr: "Bosslar",
  },
  items: {
    en: "Items",
    "zh-cn": "物品",
    "pt-br": "Itens",
    ru: "Предметы",
    de: "Gegenstände",
    es: "Objetos",
    fr: "Objets",
    ja: "アイテム",
    ko: "아이템",
    tr: "Eşyalar",
  },
  skills: {
    en: "Skills",
    "zh-cn": "技能",
    "pt-br": "Habilidades",
    ru: "Умения",
    de: "Fähigkeiten",
    es: "Habilidades",
    fr: "Compétences",
    ja: "スキル",
    ko: "스킬",
    tr: "Yetenekler",
  },
  atlas: {
    en: "Atlas",
    "zh-cn": "地图",
    "pt-br": "Atlas",
    ru: "Атлас",
    de: "Atlas",
    es: "Atlas",
    fr: "Atlas",
    ja: "アトラス",
    ko: "아틀라스",
    tr: "Atlas",
  },
  economy: {
    en: "Economy",
    "zh-cn": "经济",
    "pt-br": "Economia",
    ru: "Экономика",
    de: "Wirtschaft",
    es: "Economía",
    fr: "Économie",
    ja: "経済",
    ko: "경제",
    tr: "Ekonomi",
  },
  league: {
    en: "League",
    "zh-cn": "赛季",
    "pt-br": "Liga",
    ru: "Лига",
    de: "Liga",
    es: "Liga",
    fr: "Ligue",
    ja: "リーグ",
    ko: "리그",
    tr: "Lig",
  },
  "Release type": {
    en: "Release type",
    "zh-cn": "发布类型",
    "pt-br": "Tipo de Lançamento",
    ru: "Тип выпуска",
    de: "Veröffentlichungstyp",
    es: "Tipo de Lanzamiento",
    fr: "Type de Publication",
    ja: "リリースタイプ",
    ko: "릴리스 유형",
    tr: "Yayın Türü",
  },
  Impact: {
    en: "Impact",
    "zh-cn": "影响",
    "pt-br": "Impacto",
    ru: "Влияние",
    de: "Auswirkung",
    es: "Impacto",
    fr: "Impact",
    ja: "影響",
    ko: "영향",
    tr: "Etki",
  },
};

/** 分类页左侧 rail 筛选按钮的 10 语言显示名词表；键为 catalogConfigs 中的 filter 值。 */
export const RAIL_FILTER_LABELS_10: Record<string, TagLabel10> = {
  Equipment: {
    en: "Equipment",
    "zh-cn": "装备",
    "pt-br": "Equipamento",
    ru: "Экипировка",
    de: "Ausrüstung",
    es: "Equipo",
    fr: "Équipement",
    ja: "装備",
    ko: "장비",
    tr: "Ekipman",
  },
  Materials: {
    en: "Materials",
    "zh-cn": "材料",
    "pt-br": "Materiais",
    ru: "Материалы",
    de: "Materialien",
    es: "Materiales",
    fr: "Matériaux",
    ja: "素材",
    ko: "재료",
    tr: "Malzemeler",
  },
  Endgame: {
    en: "Endgame",
    "zh-cn": "终局",
    "pt-br": "Endgame",
    ru: "Эндгейм",
    de: "Endgame",
    es: "Endgame",
    fr: "Endgame",
    ja: "エンドゲーム",
    ko: "엔드게임",
    tr: "Endgame",
  },
  Unique: {
    en: "Unique",
    "zh-cn": "独特",
    "pt-br": "Único",
    ru: "Уникальный",
    de: "Einzigartig",
    es: "Único",
    fr: "Unique",
    ja: "ユニーク",
    ko: "고유",
    tr: "Nadir",
  },
  Currency: {
    en: "Currency",
    "zh-cn": "通货",
    "pt-br": "Moeda",
    ru: "Валюта",
    de: "Währung",
    es: "Divisa",
    fr: "Monnaie",
    ja: "通貨",
    ko: "화폐",
    tr: "Para",
  },
  Campaign: {
    en: "Campaign",
    "zh-cn": "剧情",
    "pt-br": "Campanha",
    ru: "Кампания",
    de: "Kampagne",
    es: "Campaña",
    fr: "Campagne",
    ja: "キャンペーン",
    ko: "캠페인",
    tr: "Kampanya",
  },
  Trial: {
    en: "Trial",
    "zh-cn": "试炼",
    "pt-br": "Provação",
    ru: "Испытание",
    de: "Prüfung",
    es: "Prueba",
    fr: "Épreuve",
    ja: "試練",
    ko: "시련",
    tr: "Deneme",
  },
  Pinnacle: {
    en: "Pinnacle",
    "zh-cn": "巅峰",
    "pt-br": "Ápice",
    ru: "Пик",
    de: "Gipfel",
    es: "Cúspide",
    fr: "Sommet",
    ja: "頂点",
    ko: "정점",
    tr: "Zirve",
  },
  Active: {
    en: "Active",
    "zh-cn": "主动",
    "pt-br": "Ativa",
    ru: "Активный",
    de: "Aktiv",
    es: "Activa",
    fr: "Active",
    ja: "アクティブ",
    ko: "액티브",
    tr: "Aktif",
  },
  Support: {
    en: "Support",
    "zh-cn": "辅助",
    "pt-br": "Suporte",
    ru: "Поддержка",
    de: "Unterstützung",
    es: "Soporte",
    fr: "Soutien",
    ja: "サポート",
    ko: "서포트",
    tr: "Destek",
  },
  Passive: {
    en: "Passive",
    "zh-cn": "被动",
    "pt-br": "Passiva",
    ru: "Пассивная",
    de: "Passiv",
    es: "Pasiva",
    fr: "Passif",
    ja: "パッシブ",
    ko: "패시브",
    tr: "Pasif",
  },
  Spirit: {
    en: "Spirit",
    "zh-cn": "灵魄",
    "pt-br": "Espírito",
    ru: "Дух",
    de: "Geist",
    es: "Espíritu",
    fr: "Esprit",
    ja: "スピリット",
    ko: "정신",
    tr: "Ruh",
  },
  Meta: {
    en: "Meta",
    "zh-cn": "通用",
    "pt-br": "Meta",
    ru: "Мета",
    de: "Meta",
    es: "Meta",
    fr: "Méta",
    ja: "メタ",
    ko: "메타",
    tr: "Meta",
  },
  Ascendancy: {
    en: "Ascendancy",
    "zh-cn": "升华",
    "pt-br": "Ascendência",
    ru: "Вознесение",
    de: "Aufstieg",
    es: "Ascendencia",
    fr: "Ascendance",
    ja: "アセンダンシー",
    ko: "승천",
    tr: "Yükseliş",
  },
  Lineage: {
    en: "Lineage",
    "zh-cn": "血脉",
    "pt-br": "Linhagem",
    ru: "Родословная",
    de: "Abstammung",
    es: "Linaje",
    fr: "Lignage",
    ja: "系統",
    ko: "혈통",
    tr: "Soy",
  },
  Beginner: {
    en: "Beginner",
    "zh-cn": "新手",
    "pt-br": "Iniciante",
    ru: "Новичок",
    de: "Anfänger",
    es: "Principiante",
    fr: "Débutant",
    ja: "初心者",
    ko: "초보",
    tr: "Başlangıç",
  },
  Mechanics: {
    en: "Mechanics",
    "zh-cn": "机制",
    "pt-br": "Mecânica",
    ru: "Механика",
    de: "Mechanik",
    es: "Mecánica",
    fr: "Mécanique",
    ja: "メカニクス",
    ko: "메커니즘",
    tr: "Mekanik",
  },
  Crafting: {
    en: "Crafting",
    "zh-cn": "工艺",
    "pt-br": "Fabricação",
    ru: "Создание",
    de: "Herstellung",
    es: "Fabricación",
    fr: "Artisanat",
    ja: "クラフト",
    ko: "제작",
    tr: "Üretim",
  },
  Troubleshooting: {
    en: "Troubleshooting",
    "zh-cn": "排错",
    "pt-br": "Solução de Problemas",
    ru: "Устранение неполадок",
    de: "Fehlerbehebung",
    es: "Solución de Problemas",
    fr: "Dépannage",
    ja: "トラブルシューティング",
    ko: "문제 해결",
    tr: "Sorun Giderme",
  },
  "Major Updates": {
    en: "Major Updates",
    "zh-cn": "大版本",
    "pt-br": "Atualizações Principais",
    ru: "Крупные обновления",
    de: "Große Updates",
    es: "Actualizaciones Principales",
    fr: "Mises à jour Majeures",
    ja: "メジャーアップデート",
    ko: "대형 업데이트",
    tr: "Büyük Güncellemeler",
  },
  Balance: {
    en: "Balance",
    "zh-cn": "平衡",
    "pt-br": "Equilíbrio",
    ru: "Баланс",
    de: "Balance",
    es: "Equilibrio",
    fr: "Équilibrage",
    ja: "バランス",
    ko: "밸런스",
    tr: "Denge",
  },
  Hotfixes: {
    en: "Hotfixes",
    "zh-cn": "热修",
    "pt-br": "Correções Rápidas",
    ru: "Горячие исправления",
    de: "Hotfixes",
    es: "Parches Rápidos",
    fr: "Correctifs",
    ja: "ホットフィックス",
    ko: "핫픽스",
    tr: "Acil Düzeltmeler",
  },
  "Bug Fixes": {
    en: "Bug Fixes",
    "zh-cn": "问题修复",
    "pt-br": "Correções de Erros",
    ru: "Исправления ошибок",
    de: "Fehlerbehebungen",
    es: "Corrección de Errores",
    fr: "Corrections de Bugs",
    ja: "バグ修正",
    ko: "버그 수정",
    tr: "Hata Düzeltmeleri",
  },
  Impact: {
    en: "Impact",
    "zh-cn": "影响",
    "pt-br": "Impacto",
    ru: "Влияние",
    de: "Auswirkung",
    es: "Impacto",
    fr: "Impact",
    ja: "影響",
    ko: "영향",
    tr: "Etki",
  },
  Starter: {
    en: "Starter",
    "zh-cn": "开荒",
    "pt-br": "Iniciante",
    ru: "Стартовый",
    de: "Starter",
    es: "Inicio",
    fr: "Débutant",
    ja: "スターター",
    ko: "시작",
    tr: "Başlangıç",
  },
  Leveling: {
    en: "Leveling",
    "zh-cn": "练级",
    "pt-br": "Nivelamento",
    ru: "Прокачка",
    de: "Leveln",
    es: "Subida de nivel",
    fr: "Montée de niveau",
    ja: "レベリング",
    ko: "레벨링",
    tr: "Seviye Atlama",
  },
  Bossing: {
    en: "Bossing",
    "zh-cn": "打王",
    "pt-br": "Chefes",
    ru: "Боссинг",
    de: "Bosse",
    es: "Jefes",
    fr: "Boss",
    ja: "ボス戦",
    ko: "보스",
    tr: "Boss",
  },
  Budget: {
    en: "Budget",
    "zh-cn": "预算",
    "pt-br": "Orçamento",
    ru: "Бюджет",
    de: "Budget",
    es: "Presupuesto",
    fr: "Budget",
    ja: "予算",
    ko: "예산",
    tr: "Bütçe",
  },
};

/** 将受控 tag slug 转为当前语言显示名；boss/build/item/patch 分类读取 10 语言词表，未登记时按连字符分词做标题化兜底。 */
export function formatTag(
  contentType: ContentType,
  slug: string,
  locale: ContentLocale | boolean,
): string {
  if (contentType === "boss") {
    const entry = BOSS_TAG_LABELS_10[slug];
    if (entry) {
      const localeKey = localeToTagKey(locale);
      return entry[localeKey] ?? entry.en;
    }
    return slug
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
  if (contentType === "build") {
    const entry = BUILD_TAG_LABELS_10[slug];
    if (entry) {
      const localeKey = localeToTagKey(locale);
      return entry[localeKey] ?? entry.en;
    }
    return slug
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
  if (contentType === "item") {
    const entry = ITEM_TAG_LABELS_10[slug];
    if (entry) {
      const localeKey = localeToTagKey(locale);
      return entry[localeKey] ?? entry.en;
    }
    return slug
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
  if (contentType === "guide") {
    const entry = GUIDE_TAG_LABELS_10[slug];
    if (entry) {
      const localeKey = localeToTagKey(locale);
      return entry[localeKey] ?? entry.en;
    }
    return slug
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
  if (contentType === "skill") {
    const entry = SKILL_TAG_LABELS_10[slug];
    if (entry) {
      const localeKey = localeToTagKey(locale);
      return entry[localeKey] ?? entry.en;
    }
    return slug
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
  if (contentType === "patch") {
    const entry = PATCH_TAG_LABELS_10[slug];
    if (entry) {
      const localeKey = localeToTagKey(locale);
      return entry[localeKey] ?? entry.en;
    }
    return slug
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** 将 ContentLocale | boolean 映射到 TagLabel10 的语言键，zh-cn 与 true 走中文。 */
export function localeToTagKey(locale: ContentLocale | boolean): keyof TagLabel10 {
  if (locale === "zh-cn" || locale === true) return "zh-cn";
  if (locale === "pt-br") return "pt-br";
  if (locale === "ru") return "ru";
  if (locale === "de") return "de";
  if (locale === "es") return "es";
  if (locale === "fr") return "fr";
  if (locale === "ja") return "ja";
  if (locale === "ko") return "ko";
  if (locale === "tr") return "tr";
  return "en";
}

/** 将分类带分组标题（facet）按当前语言渲染：build 分类按 facet.label.en 读取 10 语言标题，其余分类 zh-cn 取中文、其余取英文。 */
export function formatFacetLabel(
  facet: TagFacet,
  locale: ContentLocale,
): string {
  const titleEntry =
    BUILD_TAG_LABELS_10[facet.label.en] ??
    BOSS_TAG_LABELS_10[facet.label.en] ??
    ITEM_TAG_LABELS_10[facet.label.en] ??
    SKILL_TAG_LABELS_10[facet.label.en] ??
    GUIDE_TAG_LABELS_10[facet.label.en] ??
    PATCH_TAG_LABELS_10[facet.label.en];
  if (titleEntry) {
    const localeKey = localeToTagKey(locale);
    return titleEntry[localeKey] ?? titleEntry.en;
  }
  return locale === "zh-cn" ? facet.label.zh : facet.label.en;
}
